import unittest
from pathlib import Path

import sys

SYSTEM_DIR = Path(__file__).resolve().parents[1] / "services" / "report_system"
if str(SYSTEM_DIR) not in sys.path:
    sys.path.insert(0, str(SYSTEM_DIR))

from report_generator import render_html, render_markdown


class ReportGeneratorBrandingTests(unittest.TestCase):
    def test_rendered_reports_include_public_demo_author_identity(self):
        context = {
            "trade_date": "20260618",
            "report_type": "white",
            "generated_at": "2026-06-21 13:20:00",
            "overview": {
                "contracts": 7,
                "up_count": 5,
                "down_count": 2,
                "flat_count": 0,
                "avg_pct_chg": 0.39,
                "total_oi": 4651200,
                "total_vol": 123456,
            },
            "sections": "",
            "markdown_sections": "",
        }

        html = render_html(context)
        markdown = render_markdown(context)

        self.assertIn("Generated by AI Futures Data Workbench Demo · mach (@McDl11)", html)
        self.assertIn("Generated by AI Futures Data Workbench Demo · mach (@McDl11)", markdown)


if __name__ == "__main__":
    unittest.main()
